---
- name: Ensure resource group exist
  azure_rm_resourcegroup_info:
    name: "{{ resource_group }}"
  register: rg

- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
  when: rg.resourcegroups | length == 0
